services:
  - type: web
    name: divyanshu-portfolio-api
    runtime: python
    region: singapore
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CONTACT_TO_EMAIL
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
